### ISSUE TITLE
Doesn't support Java 21+

### ISSUE THREAD

**Issue by GabeCurran** [atikiNBTW/chat-on-lost-focus-fabric#1]
Trying to use the mod with a Cobblemon launcher for streaming purposes. However, getting this error.
To reproduce, install the Cobblemon Dusk modpack on Modrinth and add Chat On Lost Focus to it.

Uncaught exception in thread "main"
java.lang.RuntimeException: Error creating Mixin config chatonlostfocus.mixins.json for mod chatonlostfocus
	at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:96)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:151)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: org.spongepowered.asm.launch.MixinInitialisationError: Error initialising mixin config chatonlostfocus.mixins.json
	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:153)
	at org.spongepowered.asm.mixin.Mixins.createConfiguration(Mixins.java:100)
	at org.spongepowered.asm.mixin.Mixins.addConfiguration(Mixins.java:87)
	at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:94)
	... 3 more
Caused by: java.lang.IllegalArgumentException: The requested compatibility level JAVA_21 could not be set. Level is not supported by the active JRE or ASM version (Java 17.0, ASM 9.6 (ASM10_EXPERIMENTAL))
	at org.spongepowered.asm.mixin.MixinEnvironment.setCompatibilityLevel(MixinEnvironment.java:1627)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.initCompatibilityLevel(MixinConfig.java:557)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInit(MixinConfig.java:502)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.onLoad(MixinConfig.java:430)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.create(MixinConfig.java:1293)
	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:148)
	... 6 more

**Comment by atikiNBTW** [comment]
Hi, I think you are using the wrong version of the mod. You need to use version 1.2.3 or below, as newer versions have been updated to support java 21. Your modpack is using minecraft version 1.20.1 which only supports java 17.

**Comment by GabeCurran** [comment]
> Hi, I think you are using the wrong version of the mod. You need to use version 1.2.3 or below, as newer versions have been updated to support java 21. Your modpack is using minecraft version 1.20.1 which only supports java 17.

Ahh I see! Thank you, that's my bad. Maybe you can add this to the description?
